let divObj = document.getElementById("div");
divObj.style.backgroundColor = "yellow";
divObj.style.margin = "20px";
divObj.style.padding = "10px";
divObj.style.fontSize = "18px";
divObj.style.fontWeight = "bold";
divObj.style.height = "200px";
divObj.style.width = "300px";
divObj.style.color = "blue";